apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-gateway-token
  namespace: cloudflare-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-gateway-token
    template:
      type: Opaque
      data:
        ACCOUNT_ID: "{{ .account_id }}"
        TOKEN: "{{ .api_token }}"
  data:
    - secretKey: ACCOUNT_ID
      remoteRef:
        key: cloudflare
        property: account-id
    - secretKey: TOKEN
      remoteRef:
        key: cloudflare
        property: api-token
