apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-gateway-token
  namespace: cloudflare-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-gateway-token
  data:
    - secretKey: ACCOUNT_ID
      remoteRef:
        key: platform/cloudflare
        property: account-id
    - secretKey: TOKEN
      remoteRef:
        key: platform/cloudflare
        property: api-token
