apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: kubernetes-lab-control-plane
  namespace: default
spec:
  version: v1.31.0
  replicas: 3

  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: TinkerbellMachineTemplate
      name: pi5-controller-template

  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager: {}
      scheduler: {}
      networking:
        podSubnet: "10.244.0.0/16"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external