apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: arm64-worker-bootstrap
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TinkerbellMachineTemplate
metadata:
  name: arm64-worker-template
spec:
  template:
    spec:
      hardwareSelector:
        arch: arm64
        model: RaspberryPi5
        role: worker
      imageURL: "https://cdimage.ubuntu.com/releases/24.04.3/release/ubuntu-24.04.3-preinstalled-server-arm64+raspi.img.xz"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: kubernetes-lab-arm64-workers
spec:
  clusterName: kubernetes-lab
  replicas: 9
  selector: {}
  template:
    spec:
      version: v1.31.0
      clusterName: kubernetes-lab
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: arm64-worker-bootstrap
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: TinkerbellMachineTemplate
        name: arm64-worker-template