apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-server
  namespace: tinkerbell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifact-server
  template:
    metadata:
      labels:
        app: artifact-server
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: artifacts
              mountPath: /usr/share/nginx/html
      volumes:
        - name: artifacts
          hostPath:
            path: /var/tinkerbell/artifacts
            type: Directory