apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-backup
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-backup-credentials
      key: creds
