apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    docsUrl: https://docs.crossplane.io/v2.1/
spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane-stable
    targetRevision: 2.1.3
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
