apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            defaultReplicaCount: 2
            storageOverProvisioningPercentage: 100
            defaultDataLocality: disabled
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
