apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-components-helm
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: metallb
            wave: "0"
            repoURL: "https://metallb.github.io/metallb"
            chart: "metallb"
            revision: "0.15.3"
            namespace: "metallb-system"

          - name: rook
            wave: "0"
            repoURL: "https://github.com/evoteum/kubernetes-lab-config.git"
            path: "components/rook"
            revision: "main"
            namespace: "rook-ceph"

  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        chart: "{{chart}}"
        targetRevision: "{{revision}}"
        helm:
          releaseName: "{{name}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true