apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-lab-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/evoteum/kubernetes-lab-services.git
    targetRevision: main
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true