apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: x86-worker-bootstrap
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TinkerbellMachineTemplate
metadata:
  name: x86-worker-template
spec:
  template:
    spec:
      hardwareSelector:
        arch: x86_64
      imageURL: "https://releases.ubuntu.com/24.04.3/ubuntu-24.04.3-live-server-amd64.iso"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: kubernetes-lab-x86-workers
spec:
  clusterName: kubernetes-lab
  replicas: 2
  selector: {}
  template:
    spec:
      version: v1.31.0
      clusterName: kubernetes-lab
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: x86-worker-bootstrap
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: TinkerbellMachineTemplate
        name: x86-worker-template