apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    docsUrl: https://docs.crossplane.io/v2.3/
    bumpCount: 1
spec:
  project: default
  source:
    repoURL: https://github.com/evoteum/kubernetes-lab-config.git
    path: platform/control-plane/crossplane
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
