apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  annotations:
    docsUrl: https://external-secrets.io/latest/
    bumpCount: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/evoteum/kubernetes-lab-config.git
    path: platform/control-plane/external-secrets
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
