apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tunnel-itsbeginningtolookalotlikechristmas
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/evoteum/kubernetes-lab-config.git
    targetRevision: main
    path: platform/tunnel/itsbeginningtolookalotlikechristmas
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
