apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: k8s-07
        devices:
          - name: /dev/disk/by-id/usb-SanDisk_Extreme_XXXX
      - name: k8s-08
        devices:
          - name: /dev/disk/by-id/usb-SanDisk_Extreme_YYYY
      - name: k8s-09
        devices:
          - name: /dev/disk/by-id/usb-SanDisk_Extreme_ZZZZ
